spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: soccer11TW
    url: jdbc:mysql://localhost:3306/orthanc
  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.MySQL8Dialect

#server:
#  servlet:
#    context-path: /demo


